(defun tserg/latex-mode ()
  (setq get-buffer-compile-command
        (lambda (file) (format "pdflatex %s" file))
        )
  ;; (auto-complete-mode 1)
  ;; (ac-flyspell-workaround)
  ;; (flyspell-mode 1)
  )
(add-hook 'latex-mode-hook 'tserg/latex-mode)
(add-to-list 'auto-mode-alist '("\\.tex\\'" . tserg/latex-mode))
